# Generated by Django 3.1.3 on 2020-12-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20201226_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
