# Generated by Django 3.1.3 on 2020-11-29 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Flowers', '0002_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_by_name',
        ),
    ]
